version: '3.5'

networks:
  link_network:
    driver: bridge

services:
  library_api:
    build: ./
    container_name: library_api
    command:  ['npm', 'run', 'start:prod']
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - library_db
    networks:
      - link_network
  library_db:
    image: postgres:alpine3.18
    container_name: library_db
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - link_network
    env_file:
      - .env